import Head from "next/head";
import styles from "@/styles/Home.module.css";

import React, { useState } from "react";
import TopicSelect from "../components/TopicSelect";
import Quiz from "../components/Quiz";

const topics = [
  { value: "topic1", label: "Topic 1" },
  { value: "topic2", label: "Topic 2" },
];

const questionsData = {
  topic1: [
    {
      id: "q1",
      text: "Question 1 for Topic 1",
      choices: ["Choice 1", "Choice 2", "Choice 3"],
    },
    // Add more questions for Topic 1
  ],
  topic2: [
    {
      id: "q1",
      text: "Question 1 for Topic 2",
      choices: ["Choice 1", "Choice 2", "Choice 3"],
    },
    // Add more questions for Topic 2
  ],
};

export default function Home() {
  const [selectedTopic, setSelectedTopic] = useState(null);
  const [questions, setQuestions] = useState([]);

  const handleTopicChange = (topic) => {
    setSelectedTopic(topic);
    setQuestions(questionsData[topic.value]);
  };

  const handleSubmit = (answers) => {
    console.log("Submitted answers:", answers);
    // Implement your logic to handle the submitted answers
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Select a Topic</h1>
        <TopicSelect topics={topics} handleChange={handleTopicChange} />
        {selectedTopic && (
          <div>
            <h2>{selectedTopic.label}</h2>
            <Quiz questions={questions} handleSubmit={handleSubmit} />
          </div>
        )}
      </main>
    </>
  );
}
